# -*- coding: utf-8 -*-
"""IMDb Review and Web App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yX9VSWP9i8_2EPVKSsVyi0ioPVOlgRb_
"""

from keras.models import load_model
import joblib
from tensorflow.keras.preprocessing.sequence import pad_sequences

model = load_model("/content/IMDbModel.h5")
tokenizer = joblib.load("/content/tokenizer.pkl")

def predictive_system(review):
  sequences = tokenizer.texts_to_sequences([review])
  padded_sequence = pad_sequences(sequences,maxlen=200)
  prediction = model.predict(padded_sequence)
  sentiment = "positive"  if prediction[0][0] > 0.5 else "negative"
  return sentiment

review_sentiment = predictive_system("Beautiful cinematography")

review_sentiment

!pip install gradio

import gradio as gr
title = "Movie Sentiment Analysis"

app = gr.Interface(fn = predictive_system, inputs="textbox", outputs="textbox", title=title)

app.launch(share=True)

